### PR TITLE
Cows

### PR DESCRIPTION
**Pull request by toish**
Added cowsay to really get that authentic pointless UNIX application vibe.
- Option in `config.json`
- Added [`cowsay`](https://www.npmjs.com/package/cowsay) dependancy

### CODE REVIEW

**Comment by emctague** [comment]
Thanks! I've taken advantage of your config system to add some more options!

**Comment by emctague** [comment]
Should I gitignore that yarn.lock file or something?

**Comment by toish** [comment]
Oops sorry! You can if you want, it's used with [yarn package manager](https://yarnpkg.com/en/) it keeps dependancy versions in sync if ya use yarn, but if you don't no need to keep it around!

**Comment by emctague** [comment]
It it's useful to those who use yarn, then I guess I'll leave it in.

**Comment by toish** [comment]
It should be faster! Or at least faster ish! Has to do with how it caches + flattens dependancies etc, post an issue to https://github.com/yarnpkg/yarn if ya have a moment

**Comment by emctague** [comment]
I think I'll just give it another chance and see if it's faster now. I've switched distros (and I think I had some weird sort of setup running on the old installation that might have slowed it down...)

**Comment by emctague** [comment]
just tried it and it's actually much faster this time, thanks

**Pull request merged**
